Circ 1886 add dropdown for item service point
folio-org/mod-circulation pull request #1335
Opened 2023-09-28 02:41 UTC by rgupta-nla

## Purpose
https://issues.folio.org/browse/CIRC-1886
To populate the drop down the (ServicePoint) code will need to be used, this allows the already existing service point code to be leveraged. 

User must have the view request permission. Users: View requests, this should also limit them to their assigned service point/s. (This may need to be updated to suit general open source) This does match the generic permission in snapshot. 

## Approach
The request list is filtered in the backend based on the item selected in Primary Service Point name dropdown. 

#### TODOS and Open Questions
- [ ] Check logging

## Learning

![image](https://github.com/folio-org/mod-circulation/assets/127274721/6863462a-c023-404a-9df2-6b810f8d8e2b)

2023-09-28 05:28 UTC, fcrimmins commented on src/main/java/org/folio/circulation/domain/RequestRepresentation.java
> +    write(locationSummary, "effectiveLocationPrimaryServicePointName", location.getPrimaryServicePoint().getName());
Could getPrimaryServicePoint() sometimes return null? If so, you should probably have a null check.

2023-09-28 05:31 UTC, fcrimmins commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +          Collection<ServicePoint> spCollection = multipleServicePoints.getRecords();
I'd suggest putting some blank lines in between some of this code to make it easier to read.

2023-09-28 05:32 UTC, fcrimmins commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +              if(request.getItem().getLocation().getPrimaryServicePointId() != null &&
Similar comment to earlier about whether some null checks may be needed here?

2023-09-28 05:36 UTC, fcrimmins commented on src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
> +    final var encodedQuery = routingContext.request().getParam("effectiveLocationPrimaryServicePointId");
"effectiveLocationPrimaryServicePointId" should probably be a constant, as it is referred to in multiple places.

2023-09-28 05:39 UTC, fcrimmins commented on src/test/java/org/folio/circulation/infrastructure/storage/ServicePointRepositoryTest.java
> +    Request request = mock(Request.class);
Similar comment about putting in some blank lines to break up this large block of code.

2023-10-04 05:09 UTC, fcrimmins approved these changes

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/domain/RequestRepresentation.java
> +    if(location.getPrimaryServicePoint() != null) {
```suggestion
    if (location.getPrimaryServicePoint() != null) {
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +            if(!foundSP) {
```suggestion
            if (!foundSP) {
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +              if(request.getItem() != null && request.getItem().getLocation() != null && request.getItem().getLocation().getPrimaryServicePointId() != null &&
```suggestion
              if (request.getItem() != null && request.getItem().getLocation() != null && request.getItem().getLocation().getPrimaryServicePointId() != null &&
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +          for(Request request : requests) {
```suggestion
          for (Request request : requests) {
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +            for(ServicePoint servicePoint : spCollection) {
```suggestion
            for (ServicePoint servicePoint : spCollection) {
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +      log.info("findPrimaryServicePointsForRequests:: No service points to query");
please add empty line before return

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +    if(servicePointsToFetch.isEmpty()) {
```suggestion
    if (servicePointsToFetch.isEmpty()) {
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
> +import java.util.*;
please import only necessary classes instead of all package

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
> +    }
```suggestion
results.forEach(result -> parsedLocationIds.add(result.replace("\"", StringUtils.EMPTY)));
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/infrastructure/storage/ServicePointRepositoryTest.java
> +import static org.mockito.Mockito.*;
don't import all package

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
> +  String dec(String encodedQuery) {
why do we need package access for this method?

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
> +      });
consider moving this lambda to separate method

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/infrastructure/storage/ServicePointRepositoryTest.java
> +import org.folio.circulation.domain.*;
don't import all package

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/infrastructure/storage/ServicePointRepositoryTest.java
> +  void findPrimaryServicePointsForRequests_mismatchTest() throws Exception {
We refrain from using the '_' symbol in method names

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/infrastructure/storage/ServicePointRepositoryTest.java
> +    String name = "test name";
name of what?

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/resources/RequestCollectionResourceTest.java
> +import org.folio.circulation.domain.*;
don't import all package

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/resources/RequestCollectionResourceTest.java
> +import static org.mockito.Mockito.*;
the same as above

2023-10-05 09:51 UTC, roman-barannyk commented on src/test/java/org/folio/circulation/resources/RequestCollectionResourceTest.java
> +  void parseQueryWithThreePSPIds() {
Does it make sense to do the same as previous tests do? Maybe it makes sense to consider including inclusion within a single test?

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +      .toList();
```suggestion
List<String> servicePointsToFetch = requests.stream()
        .map(Request::getItem)
        .filter(Objects::nonNull)
        .map(Item::getLocation)
        .map(Location::getPrimaryServicePointId)
        .filter(Objects::nonNull)
        .map(Object::toString)
        .distinct()
        .toList();
```

2023-10-05 09:51 UTC, roman-barannyk commented on src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
> +          Collection<ServicePoint> spCollection = multipleServicePoints.getRecords();
consider moving this lambda into separate method

2023-10-05 13:49 UTC, alexanderkurash requested changes
Changes required

2025-03-12 13:29 UTC, alexanderkurash commented
Ticket is closed, closing the PR

2025-03-12 13:29 UTC, closed without merging